### ISSUE TITLE
question about cayman theme

### ISSUE THREAD

**Issue by zbeekman** [jasonlong/cayman-theme#10]
Hi I’ve just started looking into using jekyll and github pages and have very little web development & jekyll experience. I noticed that you can use the cayman theme with the automatic page generator, but was wondering how to integrate it with the [jekyll workflow](https://help.github.com/articles/using-jekyll-with-pages/). Right now the automatic page generator just dumps html and css into the github user/organization repository. If I start using jekyll instead of the automatic page generator, can I use the cayman theme? If so, how does one get started with this?

**Comment by jasonlong** [comment]
Hey @zbeekman. So if you decide to go with Jekyll, you'd be using that instead of the automatic page generator. That's perfectly fine and you could still use the Cayman theme. You'd just need to follow those steps to get Jekyll working and then you could grab the HTML and CSS from this repo to incorporate into your project. This shouldn't be too difficult, but it could be tricky if you haven't done much web development as you mentioned. If you get to that point, maybe open an issue on your repository and I could submit a pull request.

**Comment by zbeekman** [comment]
Thanks for the tips! I'll give it a whirl
